// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stf.DataAccess.Context;

#nullable disable

namespace stf.DataAccess.Migrations
{
    [DbContext(typeof(StarFleetDbContext))]
    [Migration("20230221134033_initialize-planets")]
    partial class initializeplanets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stf.Domain.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanetId"), 100L, 100);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planet", (string)null);

                    b.HasData(
                        new
                        {
                            PlanetId = 100,
                            Description = "A hot, arid planet with a harsh, rocky terrain. Home to the logical and stoic Vulcan species.",
                            Name = "Vulcan"
                        },
                        new
                        {
                            PlanetId = 200,
                            Description = "A beautiful planet covered in greenery and waterfalls. Home to the empathic Betazoid species.",
                            Name = "Betazed"
                        },
                        new
                        {
                            PlanetId = 300,
                            Description = "A harsh, volcanic planet with a toxic atmosphere. Home to the warrior Klingon species.",
                            Name = "Qo'noS"
                        },
                        new
                        {
                            PlanetId = 400,
                            Description = "A planet with a complex spiritual history and a strong connection to the Bajoran species' religion.",
                            Name = "Bajor"
                        },
                        new
                        {
                            PlanetId = 500,
                            Description = "A frozen planet with icy terrain and harsh weather conditions. Home to the blue-skinned Andorian species.",
                            Name = "Andoria"
                        },
                        new
                        {
                            PlanetId = 600,
                            Description = "A tropical paradise planet known for its beaches, resorts, and hedonistic culture.",
                            Name = "Risa"
                        },
                        new
                        {
                            PlanetId = 700,
                            Description = "A planet with a militaristic society and a complicated political landscape. Home to the Cardassian species.",
                            Name = "Cardassia Prime"
                        },
                        new
                        {
                            PlanetId = 800,
                            Description = "A planet known for its vast wealth and a culture centered around the accumulation of wealth. Home to the Ferengi species.",
                            Name = "Ferenginar"
                        },
                        new
                        {
                            PlanetId = 900,
                            Description = "A planet with a secretive and militaristic society. Home to the Romulan species.",
                            Name = "Romulus"
                        },
                        new
                        {
                            PlanetId = 1000,
                            Description = "A planet with a highly-developed infrastructure and a strong focus on scientific exploration. Home to the Tellarite species.",
                            Name = "Tellar Prime"
                        },
                        new
                        {
                            PlanetId = 1100,
                            Description = "A planet with a unique symbiotic species that coexists with humanoid hosts. Home to the Trill species.",
                            Name = "Trill"
                        },
                        new
                        {
                            PlanetId = 1200,
                            Description = "A planet with a hierarchical and highly-structured society. Home to the genetically-engineered Vorta species.",
                            Name = "Vorta Vor"
                        },
                        new
                        {
                            PlanetId = 1300,
                            Description = "A planet with an enigmatic and mysterious species. Little is known about the Breen and their home world.",
                            Name = "Breen"
                        },
                        new
                        {
                            PlanetId = 1400,
                            Description = "A planet with a highly-developed and technologically-advanced society. Home to the Talaxian species.",
                            Name = "Talax"
                        },
                        new
                        {
                            PlanetId = 1500,
                            Description = "A planet with a warlike and territorial species. Home to the lizard-like Gorn species.",
                            Name = "Gornar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
